### ISSUE TITLE
phyloseq_mult_raref throwing warnings

### ISSUE THREAD

**Issue by Skirnir3141** [vmikk/metagMisc#34]
Hey there, I'm running the phyloseq_mult_raref function on a fairly small phyloseq object and it's throwing some warnings. Trying to figure out why.

```
phyloseq-class experiment-level object
otu_table()   OTU Table:          [ 322 taxa and 9 samples ]:
sample_data() Sample Data:        [ 9 samples by 6 sample variables ]:
tax_table()   Taxonomy Table:     [ 322 taxa by 8 taxonomic ranks ]:
refseq()      DNAStringSet:       [ 322 reference sequences ]
```
```
metagMisc::phyloseq_mult_raref(
  ps.idataxa.t1,
  SampSize = 26049,
  MinSizeThreshold = 26049,
  iter = 1000,
  multithread = T,
  replace = F)
```
Warnings:

> > Warning messages:
> > 1: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
> > 
> > 2: <anonymous>: ... may be used in an incorrect context: ‘.fun(piece, ...)’
> 

I have the following libraries loaded:
```
library(SimpleMetaPackage)
library(dplyr)
library(decontam)
library(phyloseq)
library(ggplot2)
library(microViz)
library(metagMisc)
library(speedyseq)
```

Using R version 4.4.2 on a machine running Ubuntu 22.04.5 LTS.

Any idea what's causing the warning?

Thanks!

- Mike

**Comment by vmikk** [comment]
Hello Mike,
you may safely ignore this warning (and it will not appear if you set `multithread = FALSE`).

The warning comes from the support of additional arguments (`...`) that `phyloseq_mult_raref` may pass to `phyloseq::rarefy_even_depth`. It occurs because `...` argument is being handled withing nested functions. 

I will think how to remove it, but it does not impact the results in any way.

With kind regards,
Vladimir
